<script setup lang="ts">
import ModalCloseButton from '~/components/ui/ModalCloseButton.vue'

const props = defineProps<{ report: Record<string, any> }>()
const emit = defineEmits<{ close: []; download: [] }>()

const result = computed<Record<string, any>>(() => {
  const value = props.report.result
  if (value && typeof value === 'object') return value
  if (typeof value === 'string') {
    try { return JSON.parse(value) }
    catch { return { content: value } }
  }
  return {}
})
const members = computed(() => Array.isArray(result.value.members) ? result.value.members : [])
const summary = computed(() => result.value.summary && typeof result.value.summary === 'object' ? result.value.summary : {})
const label = (value: string) => value.replace(/_/g, ' ').replace(/\b\w/g, letter => letter.toUpperCase())
const displayValue = (value: unknown) => value === null || value === undefined || value === '' ? '—' : String(value)
const onKeydown = (event: KeyboardEvent) => { if (event.key === 'Escape') emit('close') }
onMounted(() => document.addEventListener('keydown', onKeydown))
onBeforeUnmount(() => document.removeEventListener('keydown', onKeydown))
</script>

<template>
  <div class="preview-overlay" @click.self="emit('close')">
    <section class="preview-panel" role="dialog" aria-modal="true" aria-label="Report preview">
      <header>
        <div class="min-w-0"><p>Report preview</p><h2>{{ report.name || 'Report' }}</h2><span>{{ label(String(report.report_type || 'report')) }} · {{ report.generated_at ? new Date(report.generated_at).toLocaleString() : 'Ready' }}</span></div>
        <ModalCloseButton label="Close report preview" @click="emit('close')" />
      </header>
      <main>
        <div v-if="Object.keys(summary).length" class="summary-grid">
          <article v-for="(value, key) in summary" :key="key"><small>{{ label(String(key)) }}</small><b>{{ displayValue(value) }}</b></article>
        </div>
        <section v-if="members.length" class="data-card">
          <h3>Team details</h3>
          <div class="table-wrap"><table><thead><tr><th>Name</th><th>Assigned</th><th>Completed</th><th>Effort points</th></tr></thead><tbody><tr v-for="member in members" :key="member.id || member.name"><td>{{ member.name || '—' }}</td><td>{{ displayValue(member.assigned) }}</td><td>{{ displayValue(member.completed) }}</td><td>{{ displayValue(member.effort_points) }}</td></tr></tbody></table></div>
        </section>
        <section v-else-if="result.content" class="data-card"><h3>Details</h3><p class="content">{{ result.content }}</p></section>
        <section v-else-if="!Object.keys(summary).length" class="empty">No preview data is available for this report.</section>
        <div class="meta"><span v-if="report.generated_by?.full_name">Generated by <b>{{ report.generated_by.full_name }}</b></span><span v-if="report.parameters?.start_date">{{ report.parameters.start_date }} — {{ report.parameters.end_date || 'Present' }}</span></div>
      </main>
      <footer><button type="button" class="close" @click="emit('close')">Close</button><button type="button" class="download" @click="emit('download')">Download Word</button></footer>
    </section>
  </div>
</template>

<style scoped>
.preview-overlay{position:fixed;inset:0;z-index:120;display:grid;place-items:center;padding:18px;background:rgb(15 23 42/.56);backdrop-filter:blur(4px)}
.preview-panel{display:flex;max-height:calc(100vh - 36px);width:min(920px,100%);flex-direction:column;overflow:hidden;border:1px solid #d7e2ef;border-radius:22px;background:#f7faff;color:#172033;box-shadow:0 35px 100px -30px rgb(15 23 42/.7)}
header{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;padding:22px 24px;border-bottom:1px solid #dce6f1;background:#fff}header p{font-size:12px;font-weight:800;letter-spacing:.1em;text-transform:uppercase;color:#2874d6}h2{margin-top:3px;font-size:24px;font-weight:800}header span{display:block;margin-top:5px;font-size:13px;color:#718096}
main{min-height:0;overflow:auto;padding:22px 24px}.summary-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}.summary-grid article{padding:16px;border:1px solid #dbe6f2;border-radius:14px;background:#fff}.summary-grid small{display:block;color:#718096;font-size:12px;font-weight:650}.summary-grid b{display:block;margin-top:5px;font-size:22px}
.data-card{margin-top:18px;overflow:hidden;border:1px solid #dbe6f2;border-radius:16px;background:#fff}.data-card h3{padding:15px 17px;border-bottom:1px solid #e3eaf2;font-size:16px;font-weight:800}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px 16px;border-bottom:1px solid #edf1f6;text-align:left;font-size:13px;white-space:nowrap}th{background:#f4f7fb;color:#64748b;font-weight:750}.content{padding:17px;white-space:pre-wrap;font-size:14px;line-height:1.65}.empty{padding:50px 20px;text-align:center;color:#718096}.meta{display:flex;flex-wrap:wrap;justify-content:space-between;gap:10px;margin-top:16px;color:#718096;font-size:12px}
footer{display:flex;justify-content:flex-end;gap:10px;padding:14px 24px;border-top:1px solid #dce6f1;background:#fff}footer button{height:42px;border-radius:999px;padding:0 22px;font-size:14px;font-weight:750}.close{border:1px solid #d4deea}.download{background:#2874d6;color:#fff}
:global(.tf-dark) .preview-panel{border-color:#28405d;background:#091b2e;color:#edf4ff}:global(.tf-dark) header,:global(.tf-dark) footer,:global(.tf-dark) .summary-grid article,:global(.tf-dark) .data-card{border-color:#28405d;background:#0d2036}:global(.tf-dark) .data-card h3,:global(.tf-dark) footer{border-color:#28405d}:global(.tf-dark) th{background:#132a45;color:#9fb2c8}:global(.tf-dark) td{border-color:#203852}:global(.tf-dark) header span,:global(.tf-dark) .summary-grid small,:global(.tf-dark) .meta,:global(.tf-dark) .empty{color:#95a9c0}:global(.tf-dark) .close{border-color:#38516d;background:#132a45;color:#edf4ff}
@media(max-width:640px){.preview-overlay{padding:8px}.preview-panel{max-height:calc(100vh - 16px);border-radius:17px}header,main,footer{padding-left:16px;padding-right:16px}footer button{flex:1;padding:0 12px}}
</style>
