// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/12/2026, 4:43:02 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/ilhomabdiroziqov/Desktop/task_flow_front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ilhomabdiroziqov/Desktop/task_flow_front/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ilhomabdiroziqov/Desktop/task_flow_front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ilhomabdiroziqov/Desktop/task_flow_front/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ilhomabdiroziqov/Desktop/task_flow_front/plugins/**/*.{js,ts,mjs}","/Users/ilhomabdiroziqov/Desktop/task_flow_front/composables/**/*.{js,ts,mjs}","/Users/ilhomabdiroziqov/Desktop/task_flow_front/utils/**/*.{js,ts,mjs}","/Users/ilhomabdiroziqov/Desktop/task_flow_front/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ilhomabdiroziqov/Desktop/task_flow_front/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ilhomabdiroziqov/Desktop/task_flow_front/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ilhomabdiroziqov/Desktop/task_flow_front/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;