<script setup lang="ts">
import type { ReportTemplate } from '~/composables/useReportsStore'
import AppEmptyState from '~/components/ui/AppEmptyState.vue'
import AppLoadingOverlay from '~/components/ui/AppLoadingOverlay.vue'
import AppSelect from '~/components/ui/AppSelect.vue'

const props = defineProps<{
  rows: Array<Array<string | number>>
  total: number
  pageCount: number
  pageSize: number
  searching?: boolean
}>()
const emit = defineEmits<{
  generate: [template?: ReportTemplate]
  preview: [report: Array<string | number>]
  download: [report: Array<string | number>]
  page: [page: number]
}>()
const {
  searchInput, statusFilter, sort, typeFilter, dateFilter, templates,
  summary, page, reportTypeOptions
} = useReportsStore()
const initials = (name: string) => name.split(' ').filter(Boolean).map(item => item[0]).join('').slice(0, 2) || 'U'
</script>

<template>
  <section class="tf-reports-page">
    <div class="tf-report-stats">
      <article><span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 20V4h14v16H5Zm3-5 2-3 2 2 4-5"/></svg></span><div><small>Reports generated</small><b>{{ summary.generated }}</b></div></article>
      <article><span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 4v3m14-3v3M3 9h18M4 6h16v15H4V6Z"/></svg></span><div><small>Scheduled reports</small><b>{{ summary.scheduled }}</b></div></article>
      <article><span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></span><div><small>Last generated</small><b>{{ summary.lastGenerated }}</b></div></article>
    </div>
    <div class="tf-report-template-heading"><h2>Report templates</h2><p>Start with a ready-made report</p></div>
    <div class="tf-report-templates">
      <article v-for="(template, index) in templates" :key="template.title" :class="['tf-report-template', `is-${template.tone}`]"><span class="tf-report-template-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path :d="template.icon"/></svg></span><h2>{{ template.title.replace(' Report', '') }}</h2><p>{{ template.description }}</p><em v-if="index === 0">★ Most used</em><button type="button" class="tf-report-generate" @click="emit('generate', template)">Generate</button></article>
      <article class="tf-report-template is-custom"><span class="tf-report-template-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="9"/><path d="M12 8v8M8 12h8"/></svg></span><h2>Create custom report</h2><p>Build a report tailored to your specific needs.</p><button type="button" class="tf-report-generate" @click="emit('generate')">Create custom</button></article>
    </div>
    <section class="tf-report-table-panel">
      <div class="tf-report-toolbar"><h2>Recent reports</h2><div class="tf-report-toolbar-controls"><label class="tf-report-search"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m21 21-4.3-4.3M10.5 18a7.5 7.5 0 1 1 0-15 7.5 7.5 0 0 1 0 15Z"/></svg><input v-model="searchInput" placeholder="Search reports..."/><button v-if="searchInput && !searching" type="button" aria-label="Clear report search" @click="searchInput = ''">×</button></label>
        <AppSelect v-model="typeFilter" :options="['All types', ...reportTypeOptions]" button-class="tf-report-filter" aria-label="Filter reports by type" />
        <AppSelect v-model="statusFilter" :options="['All statuses', 'Ready', 'Processing']" button-class="tf-report-filter" aria-label="Filter reports by status" />
        <AppSelect v-model="dateFilter" :options="['Last 7 days', 'Last 30 days', 'Last 90 days', 'All time']" button-class="tf-report-filter" aria-label="Filter reports by date" />
        <button type="button" class="tf-report-custom-button" @click="emit('generate')"><span>+</span> Custom report</button></div></div>
      <AppLoadingOverlay v-if="searching" label="Searching reports..." />
      <div class="tf-report-table-wrap"><table><thead><tr><th>Report name</th><th>Type</th><th><button type="button" @click="sort = sort === 'newest' ? 'oldest' : 'newest'">Date generated {{ sort === 'newest' ? '↓' : '↑' }}</button></th><th>Generated by</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="(report, index) in rows" :key="String(report[5] || report[0])"><td><b>{{ report[0] }}</b></td><td><span :class="['tf-report-type', `is-${index % 4}`]">{{ report[1] }}</span></td><td>{{ report[2] }}</td><td><span class="tf-report-person"><i>{{ initials(String(report[3] || 'User')) }}</i>{{ report[3] }}</span></td><td><span :class="['tf-report-status', String(report[4]).toLowerCase() === 'ready' ? 'is-ready' : 'is-processing']"><i/>{{ report[4] }}</span></td><td><div class="tf-report-actions"><button type="button" title="View report" @click="emit('preview', report)">◉</button><button type="button" title="Download Word report" @click="emit('download', report)">↓</button></div></td></tr></tbody></table></div>
      <AppEmptyState v-if="!rows.length && !searching" class="tf-report-empty" title="No reports found" description="Create a custom report or try another search." />
      <div v-if="rows.length" class="tf-report-pagination"><span>Showing {{ (page - 1) * pageSize + 1 }}–{{ Math.min(page * pageSize, total) }} of {{ total }} reports</span><div v-if="total > pageSize"><button type="button" @click="emit('page', page - 1)">‹</button><button v-for="item in pageCount" :key="item" :class="page === item ? 'is-active' : ''" type="button" @click="emit('page', item)">{{ item }}</button><button type="button" @click="emit('page', page + 1)">›</button></div></div>
    </section>
  </section>
</template>
